import Header from '@/components/global/header'
import '../styles/global.scss'

export const metadata = {
  title: 'Полоцкий хлебзавод',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
