import Header from '@/components/global/header'
import '../styles/global.scss'
import Footer from '@/components/global/footer'
import { usePathname } from 'next/navigation';

export const metadata = {
  title: 'Новоплоцкий хлебзавод',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const pathname = usePathname();

  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
